/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
 * Generated on: 21-Mar-2014 09:07:24
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 96
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,19 -> [-6.250000e-02 6.250000e-02)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s36,34 -> [-2 2)  (auto determined)
 *   Product         : s31,34 -> [-6.250000e-02 6.250000e-02)  (auto determined)
 *   Accumulator     : s36,34 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL12 = 96;
const int16_T B1[96] = {
    -3474,   -456,   -462,   -453,   -428,   -388,   -336,   -276,   -210,
     -144,    -83,    -32,      3,     18,      9,    -25,    -87,   -176,
     -298,   -439,   -601,   -779,   -962,  -1145,  -1316,  -1469,  -1592,
    -1677,  -1716,  -1702,  -1629,  -1494,  -1297,  -1038,   -722,   -352,
       60,    506,    974,   1450,   1921,   2372,   2790,   3161,   3474,
     3718,   3885,   3969,   3969,   3885,   3718,   3474,   3161,   2790,
     2372,   1921,   1450,    974,    506,     60,   -352,   -722,  -1038,
    -1297,  -1494,  -1629,  -1702,  -1716,  -1677,  -1592,  -1469,  -1316,
    -1145,   -962,   -779,   -601,   -439,   -298,   -176,    -87,    -25,
        9,     18,      3,    -32,    -83,   -144,   -210,   -276,   -336,
     -388,   -428,   -453,   -462,   -456,  -3474
};
