/*
* Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
* Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
* Generated on: 20-Mar-2014 16:41:55
*/

/*
* Discrete-Time FIR Filter (real)
* -------------------------------
* Filter Structure  : Direct-Form FIR
* Filter Length     : 159
* Stable            : Yes
* Linear Phase      : Yes (Type 1)
* Arithmetic        : fixed
* Numerator         : s16,15 -> [-1 1)
* Input             : s16,15 -> [-1 1)
* Filter Internals  : Full Precision
*   Output          : s33,30 -> [-4 4)  (auto determined)
*   Product         : s31,30 -> [-1 1)  (auto determined)
*   Accumulator     : s33,30 -> [-4 4)  (auto determined)
*   Round Mode      : No rounding
*   Overflow Mode   : No overflow
*/

/*
* fs = 44100 Hz
* fstop = 200 Hz (60 dB)
* fpass = 800 Hz
*/

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/*
* Expected path to tmwtypes.h
* C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h
*/
const int BL = 160;
const int16_T B[160] = {
	-572, 2, 3, 4, 6, 9, 12, 16, 20,
	25, 30, 36, 41, 48, 54, 60, 67, 73,
	79, 86, 92, 97, 102, 107, 111, 114, 117,
	118, 119, 119, 117, 114, 111, 105, 99, 91,
	81, 70, 58, 44, 29, 12, -7, -27, -48,
	-71, -95, -120, -146, -174, -202, -232, -262, -293,
	-324, -356, -388, -420, -452, -484, -516, -547, -577,
	-607, -636, -663, -690, -715, -738, -760, -781, -799,
	-816, -830, -843, -853, -861, -867, -870, 31897, -870,
	-867, -861, -853, -843, -830, -816, -799, -781, -760,
	-738, -715, -690, -663, -636, -607, -577, -547, -516,
	-484, -452, -420, -388, -356, -324, -293, -262, -232,
	-202, -174, -146, -120, -95, -71, -48, -27, -7,
	12, 29, 44, 58, 70, 81, 91, 99, 105,
	111, 114, 117, 119, 119, 118, 117, 114, 111,
	107, 102, 97, 92, 86, 79, 73, 67, 60,
	54, 48, 41, 36, 30, 25, 20, 16, 12,
	9, 6, 4, 3, 2, -572, 0
};
